service: email-service

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  stage: production

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
